name: completo_italiano
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  logger: ^2.5.0
  path_provider: ^2.1.5
  rename_app: ^1.6.2
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  custom_lint: ^0.7.5
  drift_dev: ^2.26.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  fonts:
    - family: Papyrus
      fonts:
        - asset: assets/fonts/papyrus.ttf
  assets:
    - assets/icons/
